# Generated by Django 3.2.6 on 2021-08-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ('name',), 'verbose_name': 'doctor', 'verbose_name_plural': 'doctor'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, upload_to='doctor'),
        ),
    ]
